version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "3000:3000"  # Đảm bảo rằng bạn đang map cổng đúng
    environment:
      - NODE_ENV=production
    networks:
      - nestjs-network
    volumes:
      - .:/usr/src/app
    restart: always

networks:
  nestjs-network:
    driver: bridge
